/**
 * The boot and world-loading screen.
 *
 * A loading screen has one job beyond passing the time: it has to say what is
 * happening and prove that something still is. A bar that only creeps forward
 * cannot do the second part — when terrain generation takes the main thread
 * for half a second, a bar that is merely animated in JavaScript freezes with
 * everything else and the game looks hung.
 *
 * So the moving parts are split by who drives them:
 *
 *   the checklist and bar   driven by real progress, from the loader
 *   the shimmer and the mark  CSS animations, which keep running on the
 *                             compositor while the main thread is blocked
 *   the falling blocks      a canvas, which stutters honestly when the main
 *                           thread is busy and is the only thing that should
 *
 * The stage list is the part that makes it feel deliberate rather than
 * indeterminate: naming the five things that have to happen, and ticking them
 * off, turns "please wait" into a description of the work.
 */

import { el, clear } from './dom.js';

/** Stages of the one-time application boot. */
export const BOOT_STAGES = [
  'Starting renderer',
  'Painting textures',
  'Compiling shaders',
  'Opening saves',
  'Growing a world',
];

/** Stages of loading or creating a world. */
export const WORLD_STAGES = [
  'Reading save',
  'Seeding world',
  'Generating terrain',
  'Waking the animals',
];

/**
 * Shown one at a time under the bar. Every one of these is something the game
 * actually does, so they double as a feature list for anyone reading them.
 */
const TIPS = [
  'Hold <b>Ctrl</b> while walking forward to sprint, and jump mid-sprint to clear four blocks.',
  'Villages generate in plains, savanna, forest and taiga. Try <b>/locate village</b>.',
  'Desert temples hide a treasure chamber under the floor — dig down from the middle.',
  'Sheep come in five fleeces, and the wool you get from one matches the one you saw.',
  'Every texture in this game is painted at runtime. There are no image files.',
  '<b>Settings → Shaders</b> has sun shadows, bloom and sun shafts, all separately.',
  'Shift near an edge and you will not walk off it.',
  '<b>F3</b> opens the debug overlay, <b>F5</b> changes the view, <b>F2</b> saves a screenshot.',
  'Igloos appear in snowy tundra, and there is usually a chest inside.',
  'A cobweb in a dungeon will hold you in place. Break it or go around.',
  'Terrain is a pure function of the seed, so only your edits are ever saved.',
  'Double-tap <b>Space</b> in creative to fly, then <b>Space</b> and <b>Shift</b> for up and down.',
  'The title screen is a real world, generated by the same code as the one you play.',
  'Press <b>/</b> for commands: <b>/time day</b>, <b>/tp</b>, <b>/gamemode</b>, <b>/locate</b>.',
];

/** Seconds each tip stays up. */
const TIP_SECONDS = 5;

/** Palette for the drifting blocks, muted so they never compete with the text. */
const BLOCK_COLORS = [
  ['#6f9b46', '#55793a', '#4a6a33'],
  ['#8a6540', '#6d4f31', '#5d4429'],
  ['#7c7c85', '#63636b', '#55555c'],
  ['#c3b184', '#a2946e', '#8d8160'],
  ['#5d7fa8', '#4a678a', '#3f5876'],
];

export class LoadingScreen {
  /**
   * @param {object} nodes  the boot elements from index.html
   */
  constructor(nodes) {
    this.root = nodes.root;
    this.canvas = nodes.canvas;
    this.title = nodes.title;
    this.subtitle = nodes.subtitle;
    this.stageList = nodes.stages;
    this.fill = nodes.fill;
    this.status = nodes.status;
    this.percent = nodes.percent;
    this.tip = nodes.tip;

    this.context = this.canvas?.getContext('2d') ?? null;
    this.blocks = [];
    this.stages = [];
    this.stageNodes = [];
    this.visible = true;
    this.tipIndex = Math.floor(Math.random() * TIPS.length);
    this.lastFrame = 0;
    this.tipTimer = 0;
    this.hideTimer = null;

    this.frame = this.frame.bind(this);
    if (this.context) {
      this.seedBlocks();
      requestAnimationFrame(this.frame);
    }
  }

  // -------------------------------------------------------------------------
  // Content
  // -------------------------------------------------------------------------

  /**
   * Show the screen and describe what is about to happen.
   *
   * @param {string} title
   * @param {string} subtitle
   * @param {string[]} stages  the named steps, in the order they will happen
   */
  show(title, subtitle, stages) {
    clearTimeout(this.hideTimer);
    this.visible = true;
    this.root.classList.remove('hidden', 'is-leaving');
    this.status.classList.remove('is-error');

    this.title.textContent = title;
    if (this.subtitle) this.subtitle.textContent = subtitle ?? '';

    this.setStages(stages);
    this.nextTip();
    this.tipTimer = 0;
    this.setProgress(0.02, stages[0] ?? 'Loading');
  }

  setStages(stages) {
    this.stages = [...stages];
    this.stageNodes = [];
    clear(this.stageList);
    for (const label of this.stages) {
      const node = el('li.stage', {}, [
        el('span.stage__dot'),
        el('span.stage__label', { text: label }),
      ]);
      this.stageNodes.push(node);
      this.stageList.append(node);
    }
  }

  /**
   * Move the bar, and work out which stage that puts us in.
   *
   * The status text is matched against the stage list rather than the caller
   * being asked to pass an index, so a loader can keep reporting in plain
   * English and still drive the checklist. Anything unrecognised — an error, a
   * one-off message — updates the text and leaves the ticks alone.
   */
  setProgress(fraction, status) {
    const clamped = Math.min(1, Math.max(0, Number.isFinite(fraction) ? fraction : 0));
    this.fill.style.width = `${Math.round(clamped * 100)}%`;
    if (this.percent) this.percent.textContent = `${Math.round(clamped * 100)}%`;
    if (!status) return;

    this.status.textContent = status;

    const index = this.stages.indexOf(status);
    if (index < 0) return;
    this.stageNodes.forEach((node, i) => {
      node.classList.toggle('is-done', i < index);
      node.classList.toggle('is-active', i === index);
    });
  }

  /** Mark every stage complete, for the moment before the screen leaves. */
  finish(status = 'Ready') {
    this.setProgress(1, status);
    for (const node of this.stageNodes) {
      node.classList.add('is-done');
      node.classList.remove('is-active');
    }
  }

  setError(message) {
    this.status.textContent = message;
    this.status.classList.add('is-error');
    this.fill.style.width = '100%';
  }

  clearError() {
    this.status.classList.remove('is-error');
  }

  hide() {
    this.visible = false;
    this.root.classList.add('is-leaving');
    clearTimeout(this.hideTimer);
    this.hideTimer = setTimeout(() => this.root.classList.add('hidden'), 550);
  }

  nextTip() {
    if (!this.tip) return;
    this.tipIndex = (this.tipIndex + 1) % TIPS.length;
    this.tip.classList.remove('is-in');
    // Force the transition to restart from the faded state.
    void this.tip.offsetWidth;
    this.tip.innerHTML = TIPS[this.tipIndex];
    this.tip.classList.add('is-in');
  }

  // -------------------------------------------------------------------------
  // Backdrop
  // -------------------------------------------------------------------------

  seedBlocks() {
    for (let i = 0; i < 34; i++) {
      this.blocks.push(this.makeBlock(Math.random()));
    }
  }

  /** `progress` is how far down its fall the block starts, 0..1. */
  makeBlock(progress) {
    // Depth drives size, speed and opacity together, which is the whole of the
    // parallax: near blocks are big, fast and solid, far ones small and faint.
    const depth = 0.25 + Math.random() * 0.75;
    return {
      x: Math.random(),
      y: progress,
      depth,
      size: 9 + depth * 26,
      speed: 0.012 + depth * 0.03,
      drift: (Math.random() - 0.5) * 0.02,
      spin: (Math.random() - 0.5) * 0.5,
      angle: Math.random() * Math.PI * 2,
      palette: BLOCK_COLORS[Math.floor(Math.random() * BLOCK_COLORS.length)],
    };
  }

  frame(now) {
    requestAnimationFrame(this.frame);
    if (!this.visible || !this.context) return;

    const delta = this.lastFrame ? Math.min(0.1, (now - this.lastFrame) / 1000) : 0.016;
    this.lastFrame = now;

    this.tipTimer += delta;
    if (this.tipTimer >= TIP_SECONDS) {
      this.tipTimer = 0;
      this.nextTip();
    }

    this.resizeCanvas();
    this.drawBlocks(delta);
  }

  resizeCanvas() {
    const width = this.canvas.clientWidth;
    const height = this.canvas.clientHeight;
    if (width < 1 || height < 1) return;
    const ratio = Math.min(2, window.devicePixelRatio || 1);
    const w = Math.floor(width * ratio);
    const h = Math.floor(height * ratio);
    if (this.canvas.width === w && this.canvas.height === h) return;
    this.canvas.width = w;
    this.canvas.height = h;
  }

  drawBlocks(delta) {
    const ctx = this.context;
    const { width, height } = this.canvas;
    ctx.clearRect(0, 0, width, height);

    for (const block of this.blocks) {
      block.y += block.speed * delta;
      block.x += block.drift * delta;
      block.angle += block.spin * delta;
      if (block.y > 1.15) {
        Object.assign(block, this.makeBlock(-0.15));
      }
      this.drawCube(ctx, block, width, height);
    }
  }

  /**
   * One isometric cube: three parallelograms sharing a centre.
   *
   * Drawn by hand rather than with an image because the whole game is drawn by
   * hand, and because a cube built from three lit faces reads as a block from
   * the first frame in a way a flat square never does.
   */
  drawCube(ctx, block, width, height) {
    const ratio = Math.min(2, window.devicePixelRatio || 1);
    const size = block.size * ratio;
    const x = block.x * width;
    const y = block.y * height;
    const [top, left, right] = block.palette;

    ctx.save();
    ctx.translate(x, y);
    ctx.rotate(block.angle * 0.25);
    ctx.globalAlpha = 0.1 + block.depth * 0.22;

    const w = size * 0.5;
    const h = size * 0.29;

    ctx.fillStyle = top;
    ctx.beginPath();
    ctx.moveTo(0, -h * 2);
    ctx.lineTo(w, -h);
    ctx.lineTo(0, 0);
    ctx.lineTo(-w, -h);
    ctx.closePath();
    ctx.fill();

    ctx.fillStyle = left;
    ctx.beginPath();
    ctx.moveTo(-w, -h);
    ctx.lineTo(0, 0);
    ctx.lineTo(0, size * 0.62);
    ctx.lineTo(-w, size * 0.62 - h);
    ctx.closePath();
    ctx.fill();

    ctx.fillStyle = right;
    ctx.beginPath();
    ctx.moveTo(w, -h);
    ctx.lineTo(0, 0);
    ctx.lineTo(0, size * 0.62);
    ctx.lineTo(w, size * 0.62 - h);
    ctx.closePath();
    ctx.fill();

    ctx.restore();
  }
}
